package com.miraca.eboss.demo;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(fd8f6711b2a596f1bae5000df5b0f1d1)
 */
public class CaseSource extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String caseNumber;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String caseType;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String clientCode;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.String dateOfService;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String firstName;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String lastName;
    
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.String professionalPerformed;
    
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String technicalPerformed;
    
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.String ticketNumber;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.String zipcode;

    public CaseSource() {
    }

    public CaseSource(java.lang.String caseNumber, java.lang.String caseType, java.lang.String clientCode, java.lang.String firstName, java.lang.String lastName, java.lang.String zipcode, java.lang.String dateOfService, java.lang.String technicalPerformed, java.lang.String professionalPerformed, java.lang.String ticketNumber) {
        this.caseNumber = caseNumber;
        this.caseType = caseType;
        this.clientCode = clientCode;
        this.firstName = firstName;
        this.lastName = lastName;
        this.zipcode = zipcode;
        this.dateOfService = dateOfService;
        this.technicalPerformed = technicalPerformed;
        this.professionalPerformed = professionalPerformed;
        this.ticketNumber = ticketNumber;
    }


    
    public java.lang.String getCaseNumber() {
        return this.caseNumber;
    }

    public void setCaseNumber(java.lang.String caseNumber) {
        this.caseNumber = caseNumber;
    }
    
    public java.lang.String getCaseType() {
        return this.caseType;
    }

    public void setCaseType(java.lang.String caseType) {
        this.caseType = caseType;
    }
    
    public java.lang.String getClientCode() {
        return this.clientCode;
    }

    public void setClientCode(java.lang.String clientCode) {
        this.clientCode = clientCode;
    }
    
    public java.lang.String getDateOfService() {
        return this.dateOfService;
    }

    public void setDateOfService(java.lang.String dateOfService) {
        this.dateOfService = dateOfService;
    }
    
    public java.lang.String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getLastName() {
        return this.lastName;
    }

    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public java.lang.String getProfessionalPerformed() {
        return this.professionalPerformed;
    }

    public void setProfessionalPerformed(java.lang.String professionalPerformed) {
        this.professionalPerformed = professionalPerformed;
    }
    
    public java.lang.String getTechnicalPerformed() {
        return this.technicalPerformed;
    }

    public void setTechnicalPerformed(java.lang.String technicalPerformed) {
        this.technicalPerformed = technicalPerformed;
    }
    
    public java.lang.String getTicketNumber() {
        return this.ticketNumber;
    }

    public void setTicketNumber(java.lang.String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }
    
    public java.lang.String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(java.lang.String zipcode) {
        this.zipcode = zipcode;
    }
}