package com.miraca.eboss.demo;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(9eb3913956cdd2822fb96a6432a5aab3)
 */
public class ChargeLine  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String chargeType;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String cpt;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String diagnosis;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Float price;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.Short qty;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String ticketNumber;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.Float totalPrice;

    public ChargeLine() {
    }

    public ChargeLine(java.lang.String ticketNumber, java.lang.String cpt, java.lang.String chargeType, java.lang.String diagnosis, java.lang.Short qty, java.lang.Float price, java.lang.Float totalPrice) {
        this.ticketNumber = ticketNumber;
        this.cpt = cpt;
        this.chargeType = chargeType;
        this.diagnosis = diagnosis;
        this.qty = qty;
        this.price = price;
        this.totalPrice = totalPrice;
    }


    
    public java.lang.String getChargeType() {
        return this.chargeType;
    }

    public void setChargeType(java.lang.String chargeType) {
        this.chargeType = chargeType;
    }
    
    public java.lang.String getCpt() {
        return this.cpt;
    }

    public void setCpt(java.lang.String cpt) {
        this.cpt = cpt;
    }
    
    public java.lang.String getDiagnosis() {
        return this.diagnosis;
    }

    public void setDiagnosis(java.lang.String diagnosis) {
        this.diagnosis = diagnosis;
    }
    
    public java.lang.Float getPrice() {
        return this.price;
    }

    public void setPrice(java.lang.Float price) {
        this.price = price;
    }
    
    public java.lang.Short getQty() {
        return this.qty;
    }

    public void setQty(java.lang.Short qty) {
        this.qty = qty;
    }
    
    public java.lang.String getTicketNumber() {
        return this.ticketNumber;
    }

    public void setTicketNumber(java.lang.String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }
    
    public java.lang.Float getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(java.lang.Float totalPrice) {
        this.totalPrice = totalPrice;
    }
}