package com.miraca.eboss.demo;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(dfce9867bd9eb483f6a90b36563940c3)
 */
public class Demographic  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String address;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String insurance;

    public Demographic() {
    }

    public Demographic(java.lang.String insurance, java.lang.String address) {
        this.insurance = insurance;
        this.address = address;
    }


    
    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.String getInsurance() {
        return this.insurance;
    }

    public void setInsurance(java.lang.String insurance) {
        this.insurance = insurance;
    }
}